name: Python package
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-versoin: "3.9"
      - name: Install packages
        run: pip install -r requirements.txt
      - name: Run tests
        run: python myscript.py